#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Aggregate all per-level snippets into a single L10 file for focused MCQA.

Inputs (already generated by your pipeline), per level directory:
  data/mcqa_levels/L0/L0.c            # or L0/L0_wrong.c or L0/wrong.c
  data/mcqa_levels/L1/L1.c
  ...
  data/mcqa_levels/L7/L7.c
  data/mcqa_levels/L99/L99.c

Outputs:
  data/mcqa_levels/L10/wrong.c        # concatenated C snippets
  data/mcqa_levels/L10/index.md       # optional index (function list per level)

Notes:
- Concatenation only. No rewriting of snippets.
- UTF-8 BOM to avoid mojibake in Windows editors.
"""

from pathlib import Path
import argparse
import re

LEVEL_ORDER = [f"L{i}" for i in range(0, 8)] + ["L99"]

def collect_levels(src_root: Path):
    """
    レベルディレクトリ直下に次のいずれかがあれば採用:
      - L{n}.c
      - L{n}_wrong.c
      - wrong.c
    """
    levels = []
    for p in sorted(src_root.glob("L*")):
        if not p.is_dir():
            continue
        lv = p.name  # e.g. "L1"
        candidates = [
            p / f"{lv}.c",
            p / f"{lv}_wrong.c",
            p / "wrong.c",
        ]
        if any(q.exists() for q in candidates):
            levels.append(lv)

    # 既定順 (L0..L7..L99) を優先、その他があれば後ろに
    order = [lv for lv in LEVEL_ORDER if lv in levels]
    tail = [lv for lv in levels if lv not in order]
    return order + tail

def extract_function_names(text: str):
    # lines like: // Function: FooBar
    names = []
    for line in text.splitlines():
        m = re.match(r'\s*//\s*Function:\s*(.+?)\s*$', line)
        if m:
            names.append(m.group(1).strip())
    return names

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".", type=str)
    ap.add_argument("--src-dir", default="data/mcqa_levels", type=str,
                    help="directory that has per-level snippet files under L*/")
    ap.add_argument("--out-level", default="L10", type=str,
                    help="output level directory name")
    ap.add_argument("--out-name", default="wrong.c", type=str,
                    help="output c filename")
    ap.add_argument("--make-index", action="store_true",
                    help="also write index.md with function list per level")
    args = ap.parse_args()

    root = Path(args.root)
    src_root = root / args.src_dir
    if not src_root.exists():
        raise SystemExit(f"Not found: {src_root}")

    levels = collect_levels(src_root)
    if not levels:
        raise SystemExit(
            f"No L*/(L{{n}}.c | L{{n}}_wrong.c | wrong.c) found under {src_root}"
        )

    out_dir = src_root / args.out_level
    out_dir.mkdir(parents=True, exist_ok=True)
    out_c = out_dir / args.out_name
    out_md = out_dir / "index.md"

    lines_out = []
    idx_lines = [f"# Aggregated wrong snippets → {args.out_level}", ""]
    lines_out.append(f"// === Aggregated misunderstood snippets: {args.out_level} ===")
    lines_out.append(f"// Source levels: {', '.join(levels)}")
    lines_out.append("")

    for lv in levels:
        level_dir = (src_root / lv)
        candidates = [
            level_dir / f"{lv}.c",        # e.g. data/mcqa_levels/L1/L1.c
            level_dir / f"{lv}_wrong.c",  # fallback
            level_dir / "wrong.c",        # fallback
        ]
        w = next((p for p in candidates if p.exists()), None)
        if not w:
            print(f"[WARN] skip {lv}: no {lv}.c / {lv}_wrong.c / wrong.c found")
            continue

        try:
            txt = w.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            txt = w.read_text(encoding="utf-8-sig")

        # section header per level
        sep = "/" + "*" * 78 + "/"
        lines_out.append(sep)
        lines_out.append(f"// LEVEL: {lv}")
        lines_out.append(sep)
        lines_out.append("")  # blank

        # append original content as-is (normalize EOLs)
        txt_norm = txt.replace("\r\n", "\n").replace("\r", "\n").rstrip()
        lines_out.append(txt_norm)
        lines_out.append("")  # gap

        # optional index
        if args.make_index:
            names = extract_function_names(txt_norm)
            if not names:
                idx_lines.append(f"## {lv}\n- (no function headings found)")
            else:
                idx_lines.append(f"## {lv}")
                for n in names:
                    idx_lines.append(f"- {n}")
            idx_lines.append("")

    # write outputs with BOM to avoid mojibake in Excel/Notepad
    out_c.write_text("\n".join(lines_out).rstrip() + "\n", encoding="utf-8-sig")
    if args.make_index:
        out_md.write_text("\n".join(idx_lines).rstrip() + "\n", encoding="utf-8-sig")

    print(f"[OK] Wrote: {out_c}")
    if args.make_index:
        print(f"[OK] Wrote: {out_md}")

if __name__ == "__main__":
    main()
